## NumPy

NumPy to podstawowy pakiet do obliczeń naukowych w Pythonie. Zawiera między innymi:
- wydajny n-wymiarowy obiekt tablicy
- funkcje upraszczające operacje na tablicach
- narzędzia do integracji z C/C ++ i Fortran
- operacje algebry liniowej, transformatę Fouriera i generator liczb losowych

In [1]:
import numpy as np

### Tablica

Podstawowym obiektem w NumPy jest tablica `ndarray`. Tablicę można stworzyć z kolekcji za pomocą funkcji `ndarray` lub jej aliasu `array`.

In [2]:
narr1 = np.array([1,2,3])
print(f'narr1 = {narr1}')
narr2 = np.array([[1,2],[3,4],[5,5]])
print(f'narr2 =\n{narr2}')

narr1 = [1 2 3]
narr2 =
[[1 2]
 [3 4]
 [5 5]]


In [3]:
for n in [narr1, narr2]:
    print(n)
    print(f'\tndim = {n.ndim}')
    print(f'\tshape = {n.shape}')
    print(f'\tsize = {n.size}')
    print(f'\tdtype = {n.dtype}')
    print(f'\titemsize = {n.itemsize}')
    print(f'\tdata = {n.data}')

[1 2 3]
	ndim = 1
	shape = (3,)
	size = 3
	dtype = int64
	itemsize = 8
	data = <memory at 0x70b3f49f8640>
[[1 2]
 [3 4]
 [5 5]]
	ndim = 2
	shape = (3, 2)
	size = 6
	dtype = int64
	itemsize = 8
	data = <memory at 0x70b3f49f7b90>


W przeciwieństwie do kolekcji, tablice mogą mieć tylko jeden typ elementu.

In [4]:
for val in [1, 1., 1j]:
    arr = np.array([val])
    print(f'tablica: {arr}, typ: {arr.dtype}')
# można wymusić typ przy tworzeniu tablicy
arr = np.array([123, 1], dtype=str)
print(f'tablica: {arr}, typ: {arr.dtype}')

tablica: [1], typ: int64
tablica: [1.], typ: float64
tablica: [0.+1.j], typ: complex128
tablica: ['123' '1'], typ: <U3


Ogólne metody tworzenia tablic o specyficznych właściwościach.

In [5]:
print(f'arange\n{np.arange(1,10)}')
print(f'zeros\n{np.zeros((2,3))}')
print(f'ones\n{np.ones((3,2))}')
print(f'empty\n{np.empty((2,7))}') # bez inicjalizacji
print(f'random\n{np.random.rand(2,2)}')
print(f'diag\n{np.diag([1, 2, 3, 4, 5])}')

arange
[1 2 3 4 5 6 7 8 9]
zeros
[[0. 0. 0.]
 [0. 0. 0.]]
ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]
empty
[[1.45714504e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000]]
random
[[0.61710846 0.48735707]
 [0.89277591 0.48434984]]
diag
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Pobieranie wartości z tablic.

In [10]:
print(narr1)
print(narr2)
# jak w kolekcjach
print(f'narr1[1] = {narr1[1]}')
print(f'narr2[1][1] = {narr2[1][1]}')
# lub krócej
print(f'narr2[1,1] = {narr2[1,1]}')
# przecięcia podobnie w kolekcjach
print(f'narr2[1,:] = {narr2[1,:]}')
print(f'narr2[:,1] = {narr2[:,1]}')
print(f'narr2[1,:1] = {narr2[1,:1]}')

[1 2 3]
[[1 2]
 [3 4]
 [5 5]]
narr1[1] = 2
narr2[1][1] = 4
narr2[1,1] = 4
narr2[1,:] = [3 4]
narr2[:,1] = [2 4 5]
narr2[1,:1] = [3]


Operacje w tablicach wykonywane są na poszczególnych elementach, np. jak pomnożymy dwie tablice pomnożone zostaną tylko elementy na tych samych pozycjach przez siebie.

In [11]:
a = np.random.randint(10,size=(2,3))
print(f'a =\n{a}')
print(f'a+2 =\n{a+2}')
print(f'a**2 =\n{a**2}')
print(f'a*a =\n{a*a}')

a =
[[6 7 0]
 [6 8 5]]
a+2 =
[[ 8  9  2]
 [ 8 10  7]]
a**2 =
[[36 49  0]
 [36 64 25]]
a*a =
[[36 49  0]
 [36 64 25]]


### Macierze

Numpy ma również typ macierzy `matrix`. Jest on podobny do tablicy ale podstawowe operacje wykonywane są w sposób macierzowy a nie tablicowy.

In [12]:
m1 = np.matrix([[1,2], [3,4]])
m2 = np.matrix([[5,6], [7,8]])

print(f'm1*m2 =\n{format(m1*m2)}')
print(f'm1**2 =\n{format(m1**2)}')
print(f'm1*2 =\n{format(m1*2)}')

m1*m2 =
[[19 22]
 [43 50]]
m1**2 =
[[ 7 10]
 [15 22]]
m1*2 =
[[2 4]
 [6 8]]


Tablic można używać podobnie wykorzystując odpowiednie funkcje (np. `dot`).

In [13]:
a1 = np.array([[1,2], [3,4]])
a2 = np.array([[5,6], [7,8]])

print(f'a1.dot(a2) = \n{format(a1.dot(a2))}')
print(f'a1*a2 = \n{format(a1*a2)}')
print(f'a1**2 = \n {format(a1**2)}')
print(f'a1*2 = \n{format(a1*2)}')

a1.dot(a2) = 
[[19 22]
 [43 50]]
a1*a2 = 
[[ 5 12]
 [21 32]]
a1**2 = 
 [[ 1  4]
 [ 9 16]]
a1*2 = 
[[2 4]
 [6 8]]


Operacje algebry liniowej można wykonywać zarówno na tablicach jak i macierzach

In [14]:
print(f'det(m1) = {np.linalg.det(m1):.02f}')
print(f'det(a1) = {np.linalg.det(a1):.02f}')

det(m1) = -2.00
det(a1) = -2.00


## Zadanie
Mamy liczbę trzycyfrową. Jeżeli od liczby dziesiątek odejmiemy liczbę jedności otrzymamy 6. Jeżeli do liczby dziesiątek dodamy liczbę jedności otrzymamy 10.

* znajdź wszystkie liczby trzycyfrowe spełniające ten warunek
* znajdź liczby trzycyfrowe podzielne przez 3

[Podpowiedź](https://pl.wikipedia.org/wiki/Uk%C5%82ad_r%C3%B3wna%C5%84_liniowych):
$$ Ax=B $$
$$ x = A^{-1}B $$

In [15]:
A = np.matrix([[1, -1], [1,1]])
B = np.matrix([[6], [10]])

In [16]:
A ** -1 * B

matrix([[8.],
        [2.]])

In [17]:
A = np.array([[1, -1],[1,1]])
B = np.array([[6], [10]])
x = np.linalg.inv(A).dot(B)

In [18]:
x

array([[8.],
       [2.]])

In [19]:
p = np.arange(1, 10)*100 + x[0]*10 + x[1]
p

array([182., 282., 382., 482., 582., 682., 782., 882., 982.])

In [20]:
p = p.astype('int64')
p

array([182, 282, 382, 482, 582, 682, 782, 882, 982])

In [21]:
p%3 == 0

array([False,  True, False, False,  True, False, False,  True, False])

In [22]:
p[p%3 == 0]

array([282, 582, 882])