# SciPy

Biblioteka [SciPy](https://scipy.org/) zawiera implementację wielu algorytmów z dziedziny obliczeń numerycznych. Zbudowana jest z zastosowaniem biblioteki NumPy.

W jej skład wchodzą między innymi pakiety do obliczeń statystycznych, przetwarzania sygnałów, grafiki czy optymalizacji.

### Przetwarzanie obrazów

In [6]:
%matplotlib inline
import matplotlib.pyplot as plt
import scipy

# face = scipy.misc.face # starsze wersje SciPy
face = scipy.datasets.face() # wbudowane zdjęcie (zostanie pobrane), może wymagać instalacji pakietu pooch i restartu notatników
plt.imshow(face)
plt.show()

ImportError: Missing optional dependency 'pooch' required for scipy.datasets module. Please use pip or conda to install 'pooch'.

In [7]:
from scipy import ndimage
rotated = ndimage.rotate(face, 45)
plt.imshow(rotated)
plt.show()

NameError: name 'face' is not defined

In [8]:
uniform = ndimage.uniform_filter(face)
plt.imshow(uniform)
plt.show()

NameError: name 'face' is not defined

### Algebra liniowa

Suma cyfr pewnej liczby trzycyfrowej wynosi 18. Cyfra dziesiątek jest o 1 większa od cyfry jedności. Jeśli zamienimy miejscami cyfrę setek i dziesiątek, to otrzymamy liczbę o 180 większą od początkowej. Wyznacz liczbę początkową.

$$\left\{\begin{array}{rcl}
x + y + z & = & 18\\
y - z     & = & 1\\
100x + 10y + z + 180 & = & 100y + 10x + z
\end{array} \right.$$

$$\left\{\begin{array}{rcl}
x + y + z & = & 18\\
y - z     & = & 1\\
90x - 90y & = & -180
\end{array} \right.$$

In [5]:
from scipy import linalg
import numpy as np

# zapis macierzowy
a = np.array([[1, 1, 1], [0, 1, -1], [90, -90, 0]])
b = np.array([18, 1, -180])

x = linalg.solve(a, b)

print(x)

[5. 7. 6.]


### Kombinatoryka

Ile haseł ośmioznakowych można utworzyć używając małych i wielkich liter oraz cyfr przy założeniu, że się nie powtarzają.


In [6]:
from scipy.special import perm
res = perm(26 + 26 + 10, 8)
print(res)

136325893334400.0


### Optymalizacja

Obliczenia numeryczne np. wyszukiwanie miejsc zerowych funkcji.

In [7]:
from scipy.optimize import root
import numpy as np

def func(x):
    return 2*x - 2


sol = root(func, 0.1)
print(sol)

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [ 1.000e+00]
  method: hybr
    nfev: 6
    fjac: [[-1.000e+00]]
       r: [-2.000e+00]
     qtf: [ 2.682e-08]


In [8]:
# z wykorzystaniem wyrażenia lambda
sol = root(lambda x: 2*x - 2, 0.1)
print(sol)

 message: The solution converged.
 success: True
  status: 1
     fun: [ 0.000e+00]
       x: [ 1.000e+00]
  method: hybr
    nfev: 6
    fjac: [[-1.000e+00]]
       r: [-2.000e+00]
     qtf: [ 2.682e-08]


### Algorytmy grafowe

Możliwe jest np. wyznaczanie najkrótszych ścieżek w grafie.

In [9]:
from scipy.sparse.csgraph import shortest_path
import numpy as np
# macierz sąsiedztwa z odległościami
graph = np.array([
   [0, 100, 90],
   [100, 0, 9],
   [90, 9, 0]])
print(graph)
shortest_path(graph) # macierz z najkrótszymi odległościami

[[  0 100  90]
 [100   0   9]
 [ 90   9   0]]


array([[ 0., 99., 90.],
       [99.,  0.,  9.],
       [90.,  9.,  0.]])

## SymPy

[SymPy](https://www.sympy.org) to biblioteką do obsługi obliczeń symbolicznych.

In [10]:
from sympy import Symbol, factor
x = Symbol('x')
y = Symbol('y')
print(y + x + x + 1 + x * x - y) # uproszczenie wyrażenia
print(factor(x + x + 1 + x * x)) # zamiana na iloczyn
print(factor(x * y + y * x + 1 + x ** 2 * y ** 2))

x**2 + 2*x + 1
(x + 1)**2
(x*y + 1)**2
